//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebSqlMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokoj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokoj()
        {
            this.Rezerwacja = new HashSet<Rezerwacja>();
        }
    
        public int P_ID { get; set; }
        public int P_Nr { get; set; }
        public int P_IluOsobowy { get; set; }
        public decimal P_KosztDzienny { get; set; }
        public bool P_CzyGotowy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
    }
}
